const exploreTypes = {
    FETCH_EXPLORE_START: "FETCH_EXPLORE_START",
    FETCH_EXPLORE_SUCCESS: "FETCH_EXPLORE_SUCCESS",
    FETCH_EXPLORE_FAILURE: "FETCH_EXPLORE_FAILURE"
};

export default exploreTypes;