const userTypes = {
    USER_FETCH_PENDING: "USER_FETCH_PENDING",
    USER_FETCH_START: "USER_FETCH_START",
    USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
    USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
    USER_RESET: "USER_RESET",
    CHANGE_CREDENTIALS: "CHANGE_CREDENTIALS",
    CHANGE_SUCCESS: "CHANGE_SUCCESS"
};

export default userTypes;