const userTypes = {
    USER_FETCH_PENDING: "USER_FETCH_PENDING",
    USER_FETCH_START: "USER_FETCH_START",
    USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
    USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
    USER_RESET: "USER_RESET"
};

export default userTypes;