const userTypes = {
    USER_FETCH_PENDING: "USER_FETCH_PENDING",
    USER_FETCH_START: "USER_FETCH_START",
    USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
    USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
    USER_RESET: "USER_RESET",
    CHANGE_CREDENTIALS: "CHANGE_CREDENTIALS",
    CHANGE_SUCCESS: "CHANGE_SUCCESS",
    REMOVE_INTEREST: "REMOVE_INTEREST",
    SET_INTEREST: "SET_INTEREST",
    ADD_INTEREST: "ADD_INTEREST",
    SET_PROFILE_PICTURE: "SET_PROFILE_PICTURE"
};

export default userTypes;